[app]
PageSize = 10
JwtSecret = 233
PrefixUrl = http://127.0.0.1:8000

expTime = 86400
secretkey = 1qazxsw23edcvfr45tgbnh6y7ujmki89olp0

[server]
#debug or release
RunMode = debug
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = postgres
User = ceshi
Password = ceshi
Host = 39.96.30.230:5432
Name = zy-o2o-service
TablePrefix = zy_
